# Generated by Django 4.2.5 on 2023-09-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=500)),
                (
                    "contact_time",
                    models.DateTimeField(
                        db_comment="Date and time when the article was published"
                    ),
                ),
            ],
        ),
    ]
