# Generated by Django 4.2.5 on 2023-09-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lander_page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(max_length=500),
        ),
    ]
