# Generated by Django 4.2.5 on 2023-09-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lander_page", "0002_alter_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_time",
            field=models.DateTimeField(db_comment="Date an time of contact"),
        ),
    ]
